openapi: 3.2.0
info:
  version: 2025.10.21
  title: 'Test API'
servers:
  - name: Sandbox
    url: 'https://sandbox.example.com'
    description: Sandbox
  - name: Production
    url: 'https://production.example.com'
    description: Production
paths:
  /test1:
    post:
      operationId: test1
      requestBody:
        content:
          application/json:
            examples:
              test1:
                value:
                  optionalObjectWithRequiredProp:
                    foo: foo
                    baz: BILL
            schema:
              type: object
              required:
                - requiredObject
              properties:
                requiredObject:
                  type: object
                  properties:
                    optionalProperty:
                      type: string
                optionalObject:
                  type: object
                  properties:
                    foo:
                      type: string
                optionalObjectWithRequiredProp:
                  type: object
                  required:
                    - foo
                    - baz
                  properties:
                    foo:
                      type: string
                    bar:
                      type: string
                    baz:
                      type: string
                      enum:
                        - BILL
                        - GOODS
                        - PERSON_TO_PERSON
                        - OTHER
                        - SERVICES
                      example: BILL
  /example-one-of:
    post:
      operationId: example-one-of
      requestBody:
        required: true
        content:
          application/json:
            schema:
              # required:
              #   - type
              # properties:
              #   type:
              #     type: string
              #     enum:
              #       - FOO
              #       - BAR
              #       - BAZ
              oneOf:
                - $ref: '#/components/schemas/ExampleFooRequest'
                - $ref: '#/components/schemas/ExampleBarRequest'
                - $ref: '#/components/schemas/ExampleBazRequest'
              discriminator:
                propertyName: type
                mapping:
                  FOO: '#/components/schemas/ExampleFooRequest'
                  BAR: '#/components/schemas/ExampleBarRequest'
                  BAZ: '#/components/schemas/ExampleBazRequest'
            examples:
              fooExample:
                value:
                  type: FOO
                  foo: foo
              foo2Example:
                value:
                  type: FOO
                  foo: foo2
              barExample:
                value:
                  type: BAR
                  bar: bar
              bazExample:
                value:
                  type: BAZ
                  baz: baz
  /foobar:
    post:
      servers:
        - url: 'https://foobar.example.com'
          description: FOOBAR
      tags:
        - Foobar
      summary: Foobar
      description: |
        Foobar
      operationId: post-foobar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - foo
                - bar
                - baz
              properties:
                foo:
                  description: foo.
                  type: string
                  example: foo
                bar:
                  type: string
                  description: bar.
                  example: bar
                baz:
                  type: string
                  description: baz.
                  example: baz
            examples:
              FOO:
                value:
                  foo: FOOOO
                  bar: FOOOO
                  baz: FOOOO
              BAR:
                value:
                  foo: BAAAAR
                  bar: BAAAAR
                  baz: BAAAAR
              BAZ:
                value:
                  foo: BZZZZZZ
                  bar: BZZZZZZ
                  baz: BZZZZZZ
              QUX:
                value:
                  foo: QuuuuuuuuuuuX
                  bar: QuuuuuuuuuuuX
                  baz: QuuuuuuuuuuuX
      responses:
        '200':
          description: |
            **OK** - Successful foobar attempt, returning a foobar.
          content:
            application/json:
              schema:
                type: object
                required:
                  - foo
                properties:
                  foo:
                    type: string
                    description: foo.
      security: []
components:
  schemas:
    ExampleFooRequest:
      type: object
      required:
        - type
        - foo
      properties:
        type:
          type: string
          # enum: [FOO]
          example: FOO
        foo:
          type: string
    ExampleBarRequest:
      type: object
      required:
        - type
        - bar
      properties:
        type:
          type: string
          # enum: [BAR]
          example: BAR
        bar:
          type: string
          example: test test
    ExampleBazRequest:
      type: object
      required:
        - type
        - baz
      properties:
        type:
          type: string
          # enum: [BAZ]
          example: BAZ
        baz:
          type: string
